### ISSUE TITLE
Anisotropic emitters

### ISSUE THREAD

**Issue by vsnever** [raysect/source#115]
Hello,

I’ve been playing with Raysect and wrote (actually, by copy-pasting from other classes) the uniform anisotropic surface emitter class with the user-defined spectrally inhomogeneous radiation pattern. Here are the files (with demo): [AnisotropicEmitter.zip](https://github.com/raysect/source/files/509716/AnisotropicEmitter.zip). And here is the demo GIF:
![anisotropic_emitter](https://cloud.githubusercontent.com/assets/22627041/19095924/78b38d6e-8aa1-11e6-8ad0-2a91d20ae2ab.gif)
It would be nice to have this kind of emitters in the future (after the 1.0 release, probably), e.g., to simulate the LEDs. 

Sincerely,
Vlad Neverov

**Comment by mattngc** [comment]
Dear Vlad,

Thanks for contacting us, excellent, you are our first contributor!!!

First of all we love the demo and we will definitely include something like this. You are right that we need an AnisotropicEmitter for surfaces. I guess we haven't needed this functionality yet, but because you are using it we will prioritise this feature, though we may make it more general than your current implementation. Specifically, we might add support for the azimuth and zenith angle dependence (probably with a vector instead of two explicit angles).

Thanks again, if you have any other suggestions/contributions please feel free to post them.

Regards, Alex, Matt

**Comment by vsnever** [comment]
Dear Alex and Matt,

Thank you very much for your reply!
My interest in the anisotropic emitters and the possibility of adding them to Raysect is stimulated by the stray light problem in H-alpha diagnostics in JET and ITER, the problem you are perfectly aware of. I’ve started with the simplest possible type of anisotropic emitter just to find out how hard it would be for me to understand the respective part of the code and implement the desired functionality. Thanks to the clear design and easy understanding of the code, it was not hard at all!

Since the surface emitters in Raysect are not transparent for rays, namely, the ray tracing stops when the ray hits the first surface emitter on it’s way (actually, this is quite normal behavior for a light source), it would be impossible to use them in the plasma-related problems like we did in Kurchatov Institute in our simulation of stray light in ITER with Zemax OpticStudio. Volumetric light sources should be used instead. So, this feature should not be prioritised because of this my trial of the code. However, for the engineering ray-tracer, having an anisotropic surface emitter is essential because of the LEDs, which are almost everywhere now.

Regarding the implementation, the support of the source radiation pattern as a function of two variables (zenith and azimuthal angles) may appear to be a killer feature of Raysect, because as I know in LightTools and Zemax OpticStudio, this function is not available for now. Both they support only the azimuthally symmetrical source radiation patterns.

Sincerely,
Vlad

**Comment by CnlPepper** [comment]
Functionality implemented in commit 4ae0bed2e237d7d6b3eb4be1659afdecc46a6ea5
