### ISSUE TITLE
Add a function transforming a direction vector into a rotation matrix

### ISSUE THREAD

**Issue by CocoBis** [raysect/source#12]
As the geometrical position of objects are sometimes defined through a couple position + direction, it can be nice to have a built in function calculating the rotation matrix needed to implement this kind of objects in the scenegraph. The solution matrix is the one transforming the z vector (because most of scenegraph objects are defined along the z vector) of the reference frame into the direction vector. One must be careful that there is an infinite number of solution matrix, as the direction vector define only two angles, the third one is up to the user.
This function would help a lot to place cameras or cylinders (for beams) for example.

**Comment by CnlPepper** [comment]
I've added a rotate_basis() function that takes a forward and up vector. The new coordinate space is aligned so that the +ve z-axis points along the forward direction. The up vector then defines the +ve y axis. Non-orthogonal vectors are accepted, see the doc-string for more details on how this is handled.

This function combined with translate() should achieve what you required.
