### ISSUE TITLE
Use of ConeSampler for Ray generation?

### ISSUE THREAD

**Issue by Eclipse17** [raysect/source#171]
Is it possible to use the list of Vector3D objects from ConeSampler to generate a group of rays in the Ray function? I've tried using ConeSampler, but I couldn't seem to be able to access the list. Alternately, is there a way to just generate a group of rays from a primitive object? I've been trying to simulate the light emission from a cone (a similar setup to this [image](http://scienceblogs.com/startswithabang/files/2011/05/detection.jpeg), but on a much smaller scale). Thanks!

**Comment by mattngc** [comment]
Hi Eclipse17,

The Vector and Point samplers are designed to be purely mathematical samplers. The idea is that the geometry of sampling is separated from all the mechanics of the observer making it easy to design a custom observer by bolting together different samplers in a 0D or 2D observer.

In your case, it appears the origin point of the ray cone is a constant, so you can use a constant Point3D() object as the origin of your rays. For the Vectors, the ConeSampler is the correct class to use. In the latest version of the code the name has changed to ConeUniformSampler(). You initialise this class with something like `cone_sampler = ConeUniformSampler(angle=1)`. Then you call it to generate a list with the desired number of vector samples, `vector_list = cone_sampler(50)`.

You can then make your rays by iterating through the list of vectors.

```python
origin = Point3D(your_origin)
directions = cone_sampler(ray_count)

template_ray = Ray(min_wavelength=375, max_wavelength=785)

rays = []
for n in range(ray_count):
            # Need to include sample weights from Vector sampling pdf.
            # projected area weight is normal.incident which simplifies
            # to incident.z here as the normal is (0, 0 ,1)
            rays.append((template_ray.copy(origins[n], directions[n]), directions[n].z))
```

For you application it might be better to try using the FibreOptic observer, since it has the same sampling geometry, then you don't need to create your own observer.
https://raysect.github.io/documentation/api_reference/optical/observers.html#raysect.optical.observer.nonimaging.fibreoptic.FibreOptic

There is no way to generate rays from a primitive. The Vector and Point samplers are the nuts and bolts of making a ray sampling geometry.

Does this help with your application?

**Comment by Eclipse17** [comment]
Hi mattngc,

This helps with what I need to do - thank you!
