### ISSUE TITLE
Logging material and use of Sphere Sampler

### ISSUE THREAD

**Issue by Eclipse17** [raysect/source#175]
Would it be possible to implement the Logging material (https://github.com/raysect/source/issues/98) as-is, with it just logging the hit points?

Also, would it be appropriate to use SphereSampler to generate a source that emits rays isotropically (similar to the UniformSurfaceEmitter)? Thanks!

**Comment by mattngc** [comment]
Hi Eclipse17,

Apologies, Alex and I have been quite busy lately with another project and holidays, etc. We both need to find more time to build up some momentum on these issues.

I think that the code stub in #98 doesn't really have enough functionality to generate proper spot diagrams. It was more some prototype code to get us going. Because of your interest we'll try to prioritise this and get it resolved soon. I'll have a quick look at the code I have lying around to see if I can coble together a basic demo.

Can you say a bit more about your specific use case? Do you just want to put in a primitive and get the 3D hit points? Or are you more interested in getting convention spot diagrams, e.g. hit points in a plane passing through a lens, etc.

Also, a bit confused about what you need the SphereSampler source for. For observing radiation, you can use the UniformSurfaceEmitter and UniformVolumeEmitter. If its because you want to trace the paths its easy enough to just generate a uniform distribution of vectors and launch the rays manually. If it was a common use case we could add it. What are you using it for?

Matt

**Comment by Eclipse17** [comment]
Hi Matt,

I completely understand, and my apologies for my delay in responding as well. Thanks so much for getting back to me.

For this specific case, I'm modeling how light from a point source enters the core material of a fiber optic fiber that consists of a cladding and a core. Using Raysect, I created a hollowed-out primitive box that has a second primitive box inside it. The outer hollowed-out box acts as the cladding around the inner box. This combination of objects are mounted on a crystal-like material, inside of which is the point source fo light. (see attached image)

Primarily, I just want to get 3D hit points for the locations where light would intersect the inner box (core) material. There are no lenses in the set-up, and wavelength is not a big concern right now.

The reason I asked about the SphereSampler is that I was trying to create an isotropic source of vectors and adapt the hit point demo (https://raysect.github.io/documentation/demonstrations/ray_intersection_points.html#demo-ray-intersection-points) for my situation. I was under the impression that I had to have a source of rays (rather than the UniformSurfaceEmitter or UniformVolumeEmitter) for the intersections to register. How would one go about generating the uniform distribution of rays, as you suggested?

Please let me know if you need more information!

Many thanks,
Eclipse17
![geometrysetup](https://user-images.githubusercontent.com/29437640/29034680-b10a69b8-7b5e-11e7-92ab-84a73e08145d.jpeg)

**Comment by mattngc** [comment]
Hi Eclipse17,

We've added a LoggingRay which should help with logging the 3D trajectories. See an example here:

https://github.com/raysect/source/blob/master/demos/optics/logging_trajectories.py

In this new demo we launch a set of ray paths through a glass lens and onto a target. Their trajectories are automatically logged. Its up to the user to decide what to do with the histories. In the example I use matplotlib to make a simple 3D plot of the trajectories.

For the isotropic source of of rays, just change the demo slightly. Launch all the rays from a single origin point but instead supply a list of evenly spaced isotropic vectors. Then iterate through the list of rays and launch your trajectories. We may make some helper "Light Probes" in the near future.

I think this deals with everything you are looking for functionality wise. Let us know if you still need more help.

Matt

**Comment by Eclipse17** [comment]
Hi Matt,

This is fantastic -- this does exactly what I was wanting to do.
(Just a quick note -- when I ran the logging_trajectories.py demo, it didn't show the plot. I think the demo code might be missing a plt.ioff() right before the plt.show() command.)

Thank you so much!
Eclipse17

**Comment by mattngc** [comment]
Fantastic, and thanks for spotting the bug. Let us know if you need help with anything else.
