### ISSUE TITLE
Add a spectral configuration class

### ISSUE THREAD

**Issue by mattngc** [raysect/source#20]
Passing these in as arguments occurs in many places throughout the code:
- min wavelength
- max wavelength
- number of samples

Encapsulating them in a class in raysect.optical will simplify code.

**Comment by CnlPepper** [comment]
Experimented with this and it ends up making the user interfaces less friendly.

with:
    Spectrum(SpectralConfig(100,600,10))
without:
    Spectrum(100, 600, 10)

It also makes the code slightly slower due to an extra level of pointer indirection. The only benefit is a marginal improvement in code clarity that only the developers will see.

I'm therefore closing this and tagging as won't fix.
