### ISSUE TITLE
Can MulticoreEngine retain process pool between runs?

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#227]
The motivation for requesting than scene graph objects be picklable (#226) was that there is a large overhead involved in setting up a pool of worker processes each time `MulticoreEngine.run()` is called. In the use case described in that issue, this happend inside an inner loop which called `TargettedPixel.observe()`. The observation used 1000 rays each time, but was called ~750000 times, which meant setting up and destroying worker processes ~750000 times. This process management was comparable to the run time of each observation, so the overhead was massive. Working around this requires a significant redesign of the workflow, and switching to a `SerialEngine` instead.

However, the `TargettedPixel` concerned is instantiated only once, before the loop begins. Therefore, the render engine is also instantiated only once. Would it be possible to spawn the worker processes and task and result queues in `MulticoreEngine.__init__`, and destroy them in `MulticoreEngine.__exit` instead? Then the only overhead for each observation would be moving data through the queues, which I suspect is much quicker than spawning and destroying processes.

Note that this use case is applicable to other applications with pinhole cameras. Examples are bolometry and SXR within Cherab.

**Comment by CnlPepper** [comment]
Unfortunately it isn't practically possible while retaining the ease of extension of the framework by users.

To perform a parallel calculation python must use processes to avoid the Global Interpreter Lock (GIL). Each of those processes must have exactly the same scenegraph state or the calculations from different processes would be inconsistent. When the worker processes are forked from the main process by the multicore engine, they each obtain a copy of the main process' memory (not an actual copy - see Copy on Write in linux, a logical copy so highly performant). The forking occurs as the first step in the observation loop - so we can therefore guarantee the scenegraph is identical across the processes before the observation is executed.

If we moved to a persistent worker process system, we would need to resync the state of the scenegraph. This would involve needing to serialise any changes between the independent processes. TO do this we would need to implement some for of object tracking/state delta. This would either involve a significant increase in code complexity for users (needing to implement state tracking in every scenegraph and dependent objects) or a large initialisation cost of each process before an observation (processes would need to report their current state, a comparison would need to be made with the main process state and then a resynchronisation of the new state to each worker would need to occur). The former is undesirable for obvious usability reasons. The later would almost certainly be more computationally expensive than forking due to the cost of interprocess communication.

A shared memory option would equally suffer a serialisation/deserialisation cost that would also compromise performance to a greater degree than the current forking system.

Unfortunately the specific use-case encountered by the user is better tackled by user partitioning of the work with the single core engine (avoiding the forking overhead) even if this does require more work for the user. The multicore engine is really intended for scenarios where the compute requirements of the observation greatly exceed the overhead of the process forking and ipc. 

We'll have to add some documentation addressing this use case so user are aware when it is best to switch to the single core and self partitioning approach.
