### ISSUE TITLE
Implement exp(FunctionxD)

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#309]
As discussed in #305, it would be useful to have a suite of utility functions which return the exponential of a function: `ExpXD = exp(FunctionXD.evaluate(...))`. I had something like this in mind:
```python
cdef class Exp1D(Function1D):
    """exp(f(x))"""
    cdef Function1D exponent_function

    def __init__(self, exponent_function):
        self.exponent_function = autowrap_function1d(exponent_function)

    cdef double evaluate(self, double x) except? -1e999:
        return exp(self.exponent_function.evaluate(x))


cdef class Exp2D(Function2D):
    """exp(f(x, y))"""
    cdef Function2D exponent_function

    def __init__(self, exponent_function):
        self.exponent_function = autowrap_function2d(exponent_function)

    cdef double evaluate(self, double x, double y) except? -1e999:
        return exp(self.exponent_function.evaluate(x, y))


cdef class ExpD(Function3D):
    """exp(f(x, y, z))"""
    cdef Function3D exponent_function

    def __init__(self, exponent_function):
        self.exponent_function = autowrap_function3d(exponent_function)

    cdef double evaluate(self, double x, double y, double z) except? -1e999:
        return exp(self.exponent_function.evaluate(x, y, z))
```

It would also be good to simply wrap `exp` from libc as a `Function1D` object:
```python
cdef class Exp(Function1D):
    """Wraps the exp function from <math.h> in libc"""

    cdef double evaluate(self, double x) except? -1e999:
        return exp(x)
```

**Comment by CnlPepper** [comment]
These look good. The final Exp class isn't needed however, it is covered by Exp1D(Constant1d(x)). If you add the change to the base class proposed in #307 so the autowrap functions automatically convert scalars to ConstandXD(x) then this would be simply Exp1D(x).

**Comment by CnlPepper** [comment]
Please submit a pull request against the ```feature/function branch```.

**Comment by jacklovell** [comment]
I think the final Exp class is needed, since `Exp1D(Constant1D(x0))(x)` is independent of `x`, and will instead always return `exp(x0)`. I don't think this is the intended behaviour.

Instead of `Constant1D`, the behaviour of the final `Exp` could be implemented with the following, which could be the default behaviour if the `exponent_function` argument is `None`:
```python
cdef class Identity1D(Function1D):
    cdef double evaluate(double x):
        return x

Exp = Exp1D(Identity1D())
```

Similar to the performance issues with `ConstantxD`, using `IdentityxD` in place of a scalar would result in an additional function call and likely 10-20% performance degradation. If we're happy to include the additional scalar function classes for performance reasons, I think it will be fine to have additional scalar classes for functions like `Exp`.

**Comment by CnlPepper** [comment]
I know I'm at risk of sounding inconsistent, but outside the base classes, I would expect people to use ConstantXD and not provide special cases. The reason for the special cases for the base class operations is due to their breadth of use and that the use of these classes is hidden behind the machinery of the class special methods.

I misunderstood Exp()... you want to take the exponent of the x value directly..... this would be a case for a new function. Not sure about the name. Also it is non-obvious how this scales to higher dimensions. I would think Arg1D(), Arg2D('x'), Arg2D('y') etc... would be a better name. It is essentially passing through that argument. We can figure this aspect out later, I'd just focus on the ExpXD implementation here and we can revisit the need for Identity/ArgXD in another issue.
